# Generated by Django 6.0 on 2026-01-24 15:40

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_app", "0002_rename_uploaded_at_document_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customer",
            name="uniq_customer_identity_ci",
        ),
        migrations.AddField(
            model_name="customer",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["broker", "last_name"], name="insurance_a_broker__ca2252_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("first_name"),
                django.db.models.functions.text.Lower("last_name"),
                django.db.models.functions.text.Lower("zip_code"),
                django.db.models.functions.text.Lower("street"),
                django.db.models.functions.text.Lower("street"),
                models.F("broker"),
                name="uniq_customer_identity_per_broker_ci",
            ),
        ),
    ]
