# Generated by Django 6.0 on 2025-12-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_customer_license_plate_customer_policy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Herr', 'Herr'), ('Frau', 'Frau')], max_length=10, null=True),
        ),
    ]
