# Generated by Django 6.0 on 2026-01-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_app", "0003_remove_customer_uniq_customer_identity_ci_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="appointment_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
