# Generated by Django 6.0 on 2025-12-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_alter_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contract_typ',
            field=models.CharField(blank=True, choices=[('kfz', 'Kfz-Versicherung'), ('haftpflicht', 'Privat-Haftpflicht'), ('hausrat', 'Hausrat'), ('rechtschutz', 'Rechtsschutz'), ('wohngebaeude', 'Wohngebäudeversicherung'), ('unfall', 'Unfallversicherung'), ('lebensversicherung', 'Lebensversicherung'), ('berufsunfaehigkeit', 'Berufsunfähigkeitsversicherung'), ('krankenversicherung', 'Private Krankenversicherung'), ('tierversicherung', 'Tierhalterhaftpflicht / Tierkranken'), ('reise', 'Reiseversicherung')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Aktiv'), ('ruhend', 'Ruhend')], default='aktiv', max_length=20),
        ),
    ]
