# Generated by Django 6.0 on 2025-12-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0006_document_contract_typ_document_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='status',
            new_name='contract_status',
        ),
    ]
