# Generated by Django 6.0 on 2025-12-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0008_alter_customer_city_alter_customer_customer_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active_status',
            field=models.CharField(blank=True, choices=[('aktiv', 'Aktiv'), ('ruhend', 'Ruhend')], max_length=50, null=True),
        ),
    ]
