# Generated by Django 6.0 on 2025-12-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0009_customer_active_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'zip_code', 'street'), name='uniq_customer_identity'),
        ),
    ]
