# Generated by Django 6.0 on 2025-12-16 10:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0010_customer_uniq_customer_identity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='uniq_customer_identity',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name'), django.db.models.functions.text.Lower('zip_code'), django.db.models.functions.text.Lower('street'), name='uniq_customer_identity_ci'),
        ),
    ]
