# Generated by Django 6.0 on 2025-12-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0011_remove_customer_uniq_customer_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='active_status',
            field=models.CharField(blank=True, choices=[('aktiv', 'Aktiv'), ('ruhend', 'Ruhend')], default='aktiv', max_length=50, null=True),
        ),
    ]
