# Generated by Django 6.0 on 2025-12-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0012_alter_customer_active_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_number'], name='insurance_a_custome_5287ba_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name'], name='insurance_a_last_na_8a186c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name'], name='insurance_a_first_n_ba8559_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='insurance_a_email_cebe9a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['zip_code'], name='insurance_a_zip_cod_fe38c7_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['city'], name='insurance_a_city_429ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['street'], name='insurance_a_street_1b6018_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['street', 'zip_code'], name='insurance_a_street_d7df74_idx'),
        ),
    ]
