# Generated by Django 6.0 on 2025-12-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0013_customer_insurance_a_custome_5287ba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
